import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../../../../environments/environment';

/**
 * API Endpoint Service
 * Manages API endpoint configurations
 */
@Injectable({
  providedIn: 'root'
})
export class ApiEndpointService {
  private http = inject(HttpClient);
  private baseUrl = `${environment.reportManagementApiUrl}/ReportApiEndpoint`;

  /**
   * Create a new API endpoint
   */
  create(endpoint: ApiEndpointDTO): Observable<ApiEndpointDTO> {
    return this.http.post<ApiEndpointDTO>(`${this.baseUrl}/RegisterReportApiEndpoint`, endpoint);
  }

  /**
   * Update existing API endpoint
   */
  update(id: number, endpoint: ApiEndpointDTO): Observable<ApiEndpointDTO> {
    return this.http.put<ApiEndpointDTO>(`${this.baseUrl}/UpdateReportApiEndpoint/${id}`, endpoint);
  }

  /**
   * Get API endpoint by ID
   */
  getById(id: number): Observable<ApiEndpointDTO> {
    return this.http.get<ApiEndpointDTO>(`${this.baseUrl}/RetrieveReportApiEndpointById/${id}`);
  }

  /**
   * Get all API endpoints
   */
  getAll(): Observable<ApiEndpointDTO[]> {
    return this.http.get<ApiEndpointDTO[]>(`${this.baseUrl}/RetrieveAllReportApiEndpoints`);
  }

  /**
   * Delete API endpoint
   */
  delete(id: number): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/DeleteReportApiEndpoint/${id}`);
  }

  /**
   * Test API endpoint
   */
  testEndpoint(endpoint: ApiEndpointDTO): Observable<boolean> {
    return this.http.post<boolean>(`${this.baseUrl}/Test`, endpoint);
  }
}

/**
 * Base DTO with audit fields
 */
export interface BaseDTO {
  id?: number; // Auto-generated by backend
  createdDate?: string;
  modifiedDate?: string;
  createdBy?: string;
  modifyBy?: string;
}

/**
 * API Endpoint DTO
 */
export interface ApiEndpointDTO extends BaseDTO {
  endpointName: string;
  endpointUrl: string;
  httpMethod: string;
  authenticationType: string;
  authUsername?: string;
  authPassword?: string;
  authToken?: string;
  headers?: string; // JSON format
  timeout: number;
  isDefaultEndpoint: boolean;
}
