import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../../../../environments/environment';

/**
 * Database Connection Service
 * Manages database connection configurations
 */
@Injectable({
  providedIn: 'root'
})
export class DatabaseConnectionService {
  private http = inject(HttpClient);
  private baseUrl = `${environment.reportManagementApiUrl}/DbConnections`;

  /**
   * Create a new database connection
   */
  create(connection: DatabaseConnectionDTO): Observable<DatabaseConnectionDTO> {
    return this.http.post<DatabaseConnectionDTO>(`${this.baseUrl}/RegisterDbConnection`, connection);
  }

  /**
   * Update existing database connection
   */
  update(id: number, connection: DatabaseConnectionDTO): Observable<DatabaseConnectionDTO> {
    return this.http.put<DatabaseConnectionDTO>(`${this.baseUrl}/UpdateDbConnection/${id}`, connection);
  }

  /**
   * Get database connection by ID
   */
  getById(id: number): Observable<DatabaseConnectionDTO> {
    return this.http.get<DatabaseConnectionDTO>(`${this.baseUrl}/RetrieveDbConnectionById/${id}`);
  }

  /**
   * Get all database connections
   */
  getAll(): Observable<DatabaseConnectionDTO[]> {
    return this.http.get<DatabaseConnectionDTO[]>(`${this.baseUrl}/RetrieveAllDbConnections`);
  }

  /**
   * Delete database connection
   */
  delete(id: number): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/DeleteDbConnection/${id}`);
  }

  /**
   * Test database connection
   */
  testConnection(connection: DatabaseConnectionDTO): Observable<boolean> {
    return this.http.post<boolean>(`${this.baseUrl}/TestDbConnection`, connection);
  }
}

/**
 * Base DTO with audit fields
 */
export interface BaseDTO {
  id?: number; // Auto-generated by backend
  createdDate?: string;
  modifiedDate?: string;
  createdBy?: string;
  modifyBy?: string;
}

/**
 * Database Connection DTO - Updated to match backend DTO
 */
export interface DatabaseConnectionDTO extends BaseDTO {
  connectionName: string;
  vAppName: string;
  appId: string;
  dbType: string;
  driver: string;
  host: string;
  port: string;
  service: string;
  url: string;
  username: string;
  password?: string; // Only sent on create/update, not returned
  isDefaultConnection: boolean;
  // Legacy fields for backward compatibility
  databaseType?: string;
  dbServerAddress?: string;
  databaseName?: string;
}
