/**
 * Toast placement, as a parameter instead of a hand-edited stylesheet.
 *
 * Each position maps to a `.toast-pos-*` container class generated by the
 * $toast-positions map in src/styles.scss — keep the two lists in sync.
 *
 * Usage:
 *   // app-wide: change DEFAULT_TOAST_POSITION below (one edit, every toast)
 *   // per call, via ToastHelperService:
 *   this.toast.error('Save failed', 'Error', { position: 'top-center' });
 *   // per call, injecting ToastrService directly:
 *   this.toastr.info(msg, title, { positionClass: toastPositionClass('top-right') });
 *
 * Pixel offsets, stack gap and card width are CSS custom properties
 * (--toast-offset-x / --toast-offset-y / --toast-gap / --toast-width) declared
 * on :root in styles.scss, so they can also be tuned at runtime, e.g.
 *   document.documentElement.style.setProperty('--toast-offset-y', '80px');
 */
export type ToastPosition =
  | 'top-left'
  | 'top-center'
  | 'top-right'
  | 'bottom-left'
  | 'bottom-center'
  | 'bottom-right'
  | 'center';

export const TOAST_POSITION_CLASS: Record<ToastPosition, string> = {
  'top-left': 'toast-pos-top-left',
  'top-center': 'toast-pos-top-center',
  'top-right': 'toast-pos-top-right',
  'bottom-left': 'toast-pos-bottom-left',
  'bottom-center': 'toast-pos-bottom-center',
  'bottom-right': 'toast-pos-bottom-right',
  center: 'toast-pos-center',
};

/**
 * Where toasts appear unless a call overrides it. Bottom-right keeps the
 * action-bar buttons (Save/View/Delete/Reset/Exit, top-right) clickable.
 */
export const DEFAULT_TOAST_POSITION: ToastPosition = 'top-right';

/** Where the sidebar's "new notification" popup appears. */
export const NOTIFICATION_TOAST_POSITION: ToastPosition = 'bottom-left';

export function toastPositionClass(position: ToastPosition = DEFAULT_TOAST_POSITION): string {
  return TOAST_POSITION_CLASS[position] ?? TOAST_POSITION_CLASS[DEFAULT_TOAST_POSITION];
}
