import { AdminPanelUserCase } from './admin-panel-user.model';

export const MOCK_ADMIN_PANEL_USERS: AdminPanelUserCase[] = [
  {
    userId: 'pantho',
    fullName: 'Sara Khan',
    email: 'sara.khan@example.com',
    department: 'Finance',
    role: '—',
    stage: 'Created',
    stageId: 3,
    joinDate: '2026-02-04',
    lastLogin: '2026-02-05 10:21',
    branch: 'Gulshan',
  },
  {
    userId: 'ibnul',
    fullName: 'Rahim Uddin',
    email: 'rahim.uddin@example.com',
    department: 'IT',
    role: 'Approver',
    stage: 'Authorized',
    stageId: 4,
    joinDate: '2026-02-18',
    lastLogin: '2026-08-30 09:12',
    branch: 'Dhanmondi',
  },
  {
    userId: 'rezwan',
    fullName: 'Imran Chowdhury',
    email: 'imran.chowdhury@example.com',
    department: 'Operations',
    role: 'Maker',
    stage: 'Authorized',
    stageId: 4,
    joinDate: '2026-04-09',
    lastLogin: '2026-09-05 08:33',
    branch: 'Motijheel',
  },
  {
    userId: 'zubair',
    fullName: 'Nadia Hossain',
    email: 'nadia.hossain@example.com',
    department: 'HR',
    role: 'Approver',
    stage: 'Pending',
    stageId: 5,
    joinDate: '2026-03-22',
    lastLogin: '2026-09-01 14:48',
    branch: 'Banani',
  },
  {
    userId: 'hasan',
    fullName: 'Tahmina Begum',
    email: 'tahmina.begum@example.com',
    department: 'Compliance',
    role: 'Analyst',
    stage: 'Created',
    stageId: 3,
    joinDate: '2026-05-17',
    lastLogin: '2026-08-22 16:05',
    branch: 'Head Office',
  },
];
